targets:
  $default:
    builders:
      drift_dev:
        options:
          generate_connect_constructor: false
      freezed:
        options:
          union_key: type
          union_value_case: snake
      json_serializable:
        options:
          explicit_to_json: true